In [0]:
import tensorflow as tf
tf.test.gpu_device_name()

'/device:GPU:0'

In [0]:
import xgboost as xgb
import pandas as pd
import numpy as np
import gzip
import math
import pickle
import zlib
import io
import sklearn
import torch
import torch.nn as nn
import torch.nn.functional as F
import torchvision
from matplotlib import pyplot as pt
import tensorboard
import tensorflow
from torch.utils.data import DataLoader, Dataset
import torchvision
from collections import defaultdict
from tqdm import tqdm, tqdm_notebook, tnrange

In [0]:
mkdir /root/.kaggle

In [0]:
cd /root/.kaggle

/root/.kaggle


In [0]:
from google.colab import files
files.upload()

Saving kaggle.json to kaggle.json


{'kaggle.json': b'{"username":"samuelpreethaml","key":"14617aaa25068d81fb4b1232097ec0ec"}'}

In [0]:
mkdir /root/recommender

In [0]:
cd /root/recommender

/root/recommender


In [0]:
!kaggle competitions download -c santander-product-recommendation

  0% 0.00/2.28M [00:00<?, ?B/s]
100% 2.28M/2.28M [00:00<00:00, 77.0MB/s]
 73% 9.00M/12.4M [00:00<00:00, 41.1MB/s]
100% 12.4M/12.4M [00:00<00:00, 49.2MB/s]
 94% 202M/214M [00:01<00:00, 120MB/s]
100% 214M/214M [00:01<00:00, 114MB/s]


In [0]:
!unzip train_ver2.csv.zip
!unzip test_ver2.csv.zip

Archive:  train_ver2.csv.zip
  inflating: train_ver2.csv          
Archive:  test_ver2.csv.zip
  inflating: test_ver2.csv           


In [0]:
traindata=pd.read_csv('train_ver2.csv','r',encoding='utf=8',delimiter=',')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (5,8,11,15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
headers=['Partitioned Date','Customer code','Employee index','Country residence','sex','Age','Date of First holder','New customer Index','Customer seniority','Primary Customer','Last date as primary customer','type at beginning','relation at beginning','Residence index','Foreigner index','Spouse index','channel to join','Deceased index','Addres type','Province code','Province name','Activity index','Gross income','segmentation','Saving Account','Guarantees','Current Accounts','Derivada Account','Payroll Account','Junior Account','Más particular Account','particular Account','particular Plus Account','Short-term deposits','Medium-term deposits','Long-term deposits','e-account','Funds','Mortgage','Pensions','Loans','Taxes','Credit Card','Securities','Home Account','Payroll','Pensions2','Direct Debit']

In [0]:
traindata.columns=headers

fecha_dato  ncodpers  ... ind_nom_pens_ult1 ind_recibo_ult1
0         2015-01-28   1375586  ...               0.0               0
1         2015-01-28   1050611  ...               0.0               0
2         2015-01-28   1050612  ...               0.0               0
3         2015-01-28   1050613  ...               0.0               0
4         2015-01-28   1050614  ...               0.0               0
5         2015-01-28   1050615  ...               0.0               0
6         2015-01-28   1050616  ...               0.0               0
7         2015-01-28   1050617  ...               0.0               0
8         2015-01-28   1050619  ...               0.0               0
9         2015-01-28   1050620  ...               0.0               0
10        2015-01-28   1050621  ...               0.0               0
11        2015-01-28   1050622  ...               0.0               0
12        2015-01-28   1050623  ...               0.0               0
13        2015-01-28   1050624  ...               0.0               0
14        2015-01-28   1050625  ...               0.0               0
15        2015-01-28   1050626  ...               0.0               0
16        2015-01-28   1050610  ...               0.0               0
17        2015-01-28   1050627  ...               0.0               0
18        2015-01-28   1050609  ...               0.0               0
19        2015-01-28   1050605  ...               0.0               0
20        2015-01-28   1050582  ...               0.0               0
21        2015-01-28   1050586  ...               0.0               1
22        2015-01-28   1050588  ...               0.0               0
23        2015-01-28   1050589  ...               0.0               0
24        2015-01-28   1050591  ...               0.0               0
25        2015-01-28   1050592  ...               0.0               0
26        2015-01-28   1050595  ...               0.0               0
27        2015-01-28   1050596  ...               0.0               0
28        2015-01-28   1050597  ...               0.0               0
29        2015-01-28   1050598  ...               0.0               0
...              ...       ...  ...               ...             ...
13647279  2016-05-28   1166759  ...               0.0               0
13647280  2016-05-28   1166761  ...               0.0               0
13647281  2016-05-28   1166762  ...               0.0               0
13647282  2016-05-28   1166787  ...               0.0               0
13647283  2016-05-28   1166786  ...               0.0               0
13647284  2016-05-28   1166785  ...               0.0               0
13647285  2016-05-28   1166784  ...               0.0               0
13647286  2016-05-28   1166783  ...               0.0               0
13647287  2016-05-28   1166782  ...               0.0               0
13647288  2016-05-28   1166781  ...               0.0               0
13647289  2016-05-28   1166780  ...               0.0               0
13647290  2016-05-28   1166779  ...               0.0               0
13647291  2016-05-28   1166778  ...               0.0               0
13647292  2016-05-28   1166777  ...               0.0               0
13647293  2016-05-28   1166776  ...               0.0               0
13647294  2016-05-28   1166775  ...               0.0               0
13647295  2016-05-28   1166774  ...               0.0               0
13647296  2016-05-28   1166773  ...               0.0               0
13647297  2016-05-28   1166772  ...               0.0               0
13647298  2016-05-28   1166771  ...               0.0               0
13647299  2016-05-28   1166770  ...               0.0               0
13647300  2016-05-28   1166769  ...               0.0               0
13647301  2016-05-28   1166768  ...               0.0               0
13647302  2016-05-28   1166767  ...               0.0               0
13647303  2016-05-28   1166766  ...               0.0               0
13647304  2016-05-28

In [0]:
testdata=pd.read_csv('test_ver2.csv','r',encoding='utf=8',delimiter=',')

/usr/local/lib/python3.6/dist-packages/IPython/core/interactiveshell.py:2718: DtypeWarning: Columns (15) have mixed types. Specify dtype option on import or set low_memory=False.
  interactivity=interactivity, compiler=compiler, result=result)


In [0]:
testdata.columns=headers[0:24]

In [0]:
data=pd.concat([traindata,testdata],sort=False)
data

Partitioned Date  Customer code  ... Pensions2 Direct Debit
0            2015-01-28        1375586  ...       0.0          0.0
1            2015-01-28        1050611  ...       0.0          0.0
2            2015-01-28        1050612  ...       0.0          0.0
3            2015-01-28        1050613  ...       0.0          0.0
4            2015-01-28        1050614  ...       0.0          0.0
5            2015-01-28        1050615  ...       0.0          0.0
6            2015-01-28        1050616  ...       0.0          0.0
7            2015-01-28        1050617  ...       0.0          0.0
8            2015-01-28        1050619  ...       0.0          0.0
9            2015-01-28        1050620  ...       0.0          0.0
10           2015-01-28        1050621  ...       0.0          0.0
11           2015-01-28        1050622  ...       0.0          0.0
12           2015-01-28        1050623  ...       0.0          0.0
13           2015-01-28        1050624  ...       0.0          0.0
14           2015-01-28        1050625  ...       0.0          0.0
15           2015-01-28        1050626  ...       0.0          0.0
16           2015-01-28        1050610  ...       0.0          0.0
17           2015-01-28        1050627  ...       0.0          0.0
18           2015-01-28        1050609  ...       0.0          0.0
19           2015-01-28        1050605  ...       0.0          0.0
20           2015-01-28        1050582  ...       0.0          0.0
21           2015-01-28        1050586  ...       0.0          1.0
22           2015-01-28        1050588  ...       0.0          0.0
23           2015-01-28        1050589  ...       0.0          0.0
24           2015-01-28        1050591  ...       0.0          0.0
25           2015-01-28        1050592  ...       0.0          0.0
26           2015-01-28        1050595  ...       0.0          0.0
27           2015-01-28        1050596  ...       0.0          0.0
28           2015-01-28        1050597  ...       0.0          0.0
29           2015-01-28        1050598  ...       0.0          0.0
...                 ...            ...  ...       ...          ...
929585       2016-06-28         660255  ...       NaN          NaN
929586       2016-06-28         659581  ...       NaN          NaN
929587       2016-06-28         660253  ...       NaN          NaN
929588       2016-06-28         660244  ...       NaN          NaN
929589       2016-06-28         660181  ...       NaN          NaN
929590       2016-06-28         660185  ...       NaN          NaN
929591       2016-06-28         660186  ...       NaN          NaN
929592       2016-06-28         660188  ...       NaN          NaN
929593       2016-06-28         660189  ...       NaN          NaN
929594       2016-06-28         660190  ...       NaN          NaN
929595       2016-06-28         660191  ...       NaN          NaN
929596       2016-06-28         660193  ...       NaN          NaN
929597       2016-06-28         660194  ...       NaN          NaN
929598       2016-06-28         660195  ...       NaN          NaN
929599       2016-06-28         660197  ...       NaN          NaN
929600       2016-06-28         660198  ...       NaN          NaN
929601       2016-06-28         660208  ...       NaN          NaN
929602       2016-06-28         660212  ...       NaN          NaN
929603       2016-06-28         660213  ...       NaN          NaN
929604       2016-06-28         660217  ...       NaN          NaN
929605       2016-06-28         660223  ...       NaN          NaN
929606       2016-06-28         660224  ...       NaN          NaN
929607       2016-06-28         660225  ...       NaN          NaN
929608       2016-06-28         660231  ...       NaN          NaN
929609       2016-06-28         660235  ...       NaN          NaN
929610       2016-06-28         660237  ...       NaN          NaN
929611       2016-06-28         660238  ...       NaN          NaN
929612       2016-06-28         660240  ...       NaN 

In [0]:
del(traindata)
del(testdata)

In [0]:
del(data['Employee index'])
del(data['Country residence'])
del(data['Date of First holder'])
del(data['Primary Customer'])
del(data['Last date as primary customer'])
del(data['type at beginning'])
del(data['Residence index'])
del(data['Spouse index'])
del(data['Deceased index'])
del(data['Addres type'])
del(data['Province name'])
data['Total Purchases']=data.iloc[:,-24:].sum(axis=1)
data

Partitioned Date  Customer code  ... Direct Debit Total Purchases
0            2015-01-28        1375586  ...          0.0             1.0
1            2015-01-28        1050611  ...          0.0             1.0
2            2015-01-28        1050612  ...          0.0             1.0
3            2015-01-28        1050613  ...          0.0             1.0
4            2015-01-28        1050614  ...          0.0             1.0
5            2015-01-28        1050615  ...          0.0             1.0
6            2015-01-28        1050616  ...          0.0             1.0
7            2015-01-28        1050617  ...          0.0             1.0
8            2015-01-28        1050619  ...          0.0             1.0
9            2015-01-28        1050620  ...          0.0             1.0
10           2015-01-28        1050621  ...          0.0             1.0
11           2015-01-28        1050622  ...          0.0             1.0
12           2015-01-28        1050623  ...          0.0             1.0
13           2015-01-28        1050624  ...          0.0             1.0
14           2015-01-28        1050625  ...          0.0             1.0
15           2015-01-28        1050626  ...          0.0             1.0
16           2015-01-28        1050610  ...          0.0             1.0
17           2015-01-28        1050627  ...          0.0             1.0
18           2015-01-28        1050609  ...          0.0             1.0
19           2015-01-28        1050605  ...          0.0             1.0
20           2015-01-28        1050582  ...          0.0             1.0
21           2015-01-28        1050586  ...          1.0             2.0
22           2015-01-28        1050588  ...          0.0             1.0
23           2015-01-28        1050589  ...          0.0             1.0
24           2015-01-28        1050591  ...          0.0             1.0
25           2015-01-28        1050592  ...          0.0             1.0
26           2015-01-28        1050595  ...          0.0             1.0
27           2015-01-28        1050596  ...          0.0             1.0
28           2015-01-28        1050597  ...          0.0             1.0
29           2015-01-28        1050598  ...          0.0             1.0
...                 ...            ...  ...          ...             ...
929585       2016-06-28         660255  ...          NaN             0.0
929586       2016-06-28         659581  ...          NaN             0.0
929587       2016-06-28         660253  ...          NaN             0.0
929588       2016-06-28         660244  ...          NaN             0.0
929589       2016-06-28         660181  ...          NaN             0.0
929590       2016-06-28         660185  ...          NaN             0.0
929591       2016-06-28         660186  ...          NaN             0.0
929592       2016-06-28         660188  ...          NaN             0.0
929593       2016-06-28         660189  ...          NaN             0.0
929594       2016-06-28         660190  ...          NaN             0.0
929595       2016-06-28         660191  ...          NaN             0.0
929596       2016-06-28         660193  ...          NaN             0.0
929597       2016-06-28         660194  ...          NaN             0.0
929598       2016-06-28         660195  ...          NaN             0.0
929599       2016-06-28         660197  ...          NaN             0.0
929600       2016-06-28         660198  ...          NaN             0.0
929601       2016-06-28         660208  ...          NaN             0.0
929602       2016-06-28         660212  ...          NaN             0.0
929603       2016-06-28         660213  ...          NaN             0.0
929604       2016-06-28         660217  ...          NaN             0.0
929605       2016-06-28         660223  ...          NaN             0.0
929606       2016-06-28         660224  ...          NaN             0.0
929607       2016-06-28         660225  ...          NaN         

In [0]:
def label_encode(df, features, name):
    df[name] = df[name].astype('str')
    if name in transformers: # test
        df[name] = transformers[name].transform(df[name])
    else: # train
        transformers[name] = sklearn.preprocessing.LabelEncoder()
        df[name] = transformers[name].fit_transform(df[name])
    features.append(name)

In [0]:
features=[]
transformers={}
data["code"]=data["Customer code"]
data["Gross income"].fillna(1.0, inplace=True)
data["Gross income"]=data["Gross income"].replace('         NA',data["Gross income"].value_counts().index[0])
data['Gross income']=data['Gross income'].map(lambda x :float(x))
data["Customer seniority"]=data["Customer seniority"].replace('     NA',0)
data['Customer seniority']=data['Customer seniority'].map(lambda x :int(x))
data["Customer seniority"]=data["Customer seniority"].replace(-999999,0)
data['Customer seniority']=data['Customer seniority'].map(lambda x :int(x))
data['sex'].fillna(data['sex'].value_counts().index[0],inplace=True)
data['Age']=data['Age'].replace(' NA',data['Age'].value_counts().index[0])
data['Age']=data['Age'].map(lambda x :int(x))
data['relation at beginning'].fillna(data['relation at beginning'].value_counts().index[0],inplace=True)
data['channel to join'].fillna(data['channel to join'].value_counts().index[0],inplace=True)
data['Foreigner index'].fillna(data['Foreigner index'].value_counts().index[0],inplace=True)
data['Province code'].fillna(data['Province code'].value_counts().index[0],inplace=True)
data['Activity index'].fillna(data['Province code'].value_counts().index[0],inplace=True)
data['segmentation'].fillna(data['segmentation'].value_counts().index[0],inplace=True)
label_encode(data, features, "channel to join") # simple label encode
# label_encode(data, features, "nomprov") # use cod_prov only
label_encode(data, features, 'Activity index')
label_encode(data, features, "Foreigner index")
label_encode(data, features, "sex",)
label_encode(data, features, "segmentation")
label_encode(data, features, "relation at beginning")
label_encode(data, features, "Customer code")
data['New customer Index'].fillna(0,inplace=True)
data["Partitioned Month"] = data["Partitioned Date"].map(lambda x: int(x.split("-")[1])).astype(np.int8)
data["Partitioned Month"]=data["Partitioned Month"].map(lambda x:x-1)
data["Partitioned Year"] = data["Partitioned Date"].map(lambda x: int(x.split("-")[0])).astype(np.int64)
label_encode(data, features, "Partitioned Year")
del(data["Partitioned Date"])


NameError: ignored

In [0]:
data=data[['code','Partitioned Month', 'Partitioned Year', "Customer code",'sex', 'Age', 'New customer Index','Customer seniority', 'relation at beginning', 'Foreigner index','channel to join', 'Province code', 'Activity index','Gross income','segmentation','Total Purchases','Saving Account', 'Guarantees', 'Current Accounts','Derivada Account', 'Payroll Account', 'Junior Account','Más particular Account', 'particular Account','particular Plus Account', 'Short-term deposits','Medium-term deposits', 'Long-term deposits', 'e-account', 'Funds','Mortgage', 'Pensions', 'Loans', 'Taxes', 'Credit Card', 'Securities','Home Account', 'Payroll', 'Pensions2', 'Direct Debit']]
train=data[:(14576924 -929615)]
test=data[(14576924 -929615):]

In [0]:
train["Payroll"].fillna(0, inplace=True)
train['Pensions2'].fillna(0, inplace=True)
train.drop(train[train['Total Purchases'] == 0].index, inplace = True)

/usr/local/lib/python3.6/dist-packages/pandas/core/generic.py:6130: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  self._update_inplace(new_data)
/usr/local/lib/python3.6/dist-packages/pandas/core/frame.py:3940: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  errors=errors)


In [0]:
train

code  Partitioned Month  ...  Pensions2  Direct Debit
0         1375586                  0  ...        0.0           0.0
1         1050611                  0  ...        0.0           0.0
2         1050612                  0  ...        0.0           0.0
3         1050613                  0  ...        0.0           0.0
4         1050614                  0  ...        0.0           0.0
5         1050615                  0  ...        0.0           0.0
6         1050616                  0  ...        0.0           0.0
7         1050617                  0  ...        0.0           0.0
8         1050619                  0  ...        0.0           0.0
9         1050620                  0  ...        0.0           0.0
10        1050621                  0  ...        0.0           0.0
11        1050622                  0  ...        0.0           0.0
12        1050623                  0  ...        0.0           0.0
13        1050624                  0  ...        0.0           0.0
14        1050625                  0  ...        0.0           0.0
15        1050626                  0  ...        0.0           0.0
16        1050610                  0  ...        0.0           0.0
17        1050627                  0  ...        0.0           0.0
18        1050609                  0  ...        0.0           0.0
19        1050605                  0  ...        0.0           0.0
20        1050582                  0  ...        0.0           0.0
21        1050586                  0  ...        0.0           1.0
22        1050588                  0  ...        0.0           0.0
23        1050589                  0  ...        0.0           0.0
24        1050591                  0  ...        0.0           0.0
25        1050592                  0  ...        0.0           0.0
26        1050595                  0  ...        0.0           0.0
27        1050596                  0  ...        0.0           0.0
28        1050597                  0  ...        0.0           0.0
29        1050598                  0  ...        0.0           0.0
...           ...                ...  ...        ...           ...
13647272  1166738                  4  ...        0.0           0.0
13647276  1166734                  4  ...        0.0           0.0
13647279  1166759                  4  ...        0.0           0.0
13647280  1166761                  4  ...        0.0           0.0
13647282  1166787                  4  ...        0.0           0.0
13647283  1166786                  4  ...        0.0           0.0
13647284  1166785                  4  ...        0.0           0.0
13647285  1166784                  4  ...        0.0           0.0
13647286  1166783                  4  ...        0.0           0.0
13647287  1166782                  4  ...        0.0           0.0
13647288  1166781                  4  ...        0.0           0.0
13647289  1166780                  4  ...        0.0           0.0
13647290  1166779                  4  ...        0.0           0.0
13647291  1166778                  4  ...        0.0           0.0
13647292  1166777                  4  ...        0.0           0.0
13647293  1166776                  4  ...        0.0           0.0
13647294  1166775                  4  ...        0.0           0.0
13647295  1166774                  4  ...        0.0           0.0
13647297  1166772                  4  ...        0.0           0.0
13647298  1166771                  4  ...        0.0           0.0
13647299  1166770                  4  ...        0.0           0.0
13647300  1166769                  4  ...        0.0           0.0
13647301  1166768                  4  ...        0.0           0.0
13647302  1166767                  4  ...        0.0           0.0
13647303  1166766                  4  ...        0.0           0.0
13647304  1166765                  4  ...        0.0           0.0
13647305  1166764                  4  ...        0.0           0.0
13647306  1166763                  4  ...        0.0        

In [0]:
catf=['Partitioned Month','Partitioned Year',"Customer code",'sex','New customer Index', 'relation at beginning','Foreigner index',  'channel to join', 'Province code', 'Activity index','segmentation']
conf=[col for col in train.columns[1:15] if col not in catf]
X_train, X_test, y_train, y_test = sklearn.model_selection.train_test_split(train.iloc[:,1:15], train.iloc[:,16:],test_size=0.25, random_state=42)
X_train

Partitioned Month  Partitioned Year  ...  Gross income  segmentation
2720121                   4                 0  ...     121641.81             1
6642380                   9                 0  ...          1.00             1
3162006                   5                 0  ...     117846.45             2
9758451                   0                 1  ...      80373.60             1
8991745                  11                 0  ...          1.00             2
11480397                  2                 1  ...      84269.10             1
10159802                  1                 1  ...     115932.87             1
8535838                  11                 0  ...     196893.63             1
9731293                   0                 1  ...      50217.69             1
12770625                  4                 1  ...      57855.87             1
8670476                  11                 0  ...     103540.11             0
9949268                   1                 1  ...      52455.12             2
1364380                   2                 0  ...     166633.17             1
4114442                   6                 0  ...     224667.24             1
12010139                  3                 1  ...          1.00             1
3956815                   6                 0  ...     100088.40             1
13365592                  4                 1  ...      55150.14             2
544338                    0                 0  ...          1.00             0
8535219                  11                 0  ...     135360.24             1
3388551                   5                 0  ...      91499.37             2
5691727                   8                 0  ...     209233.17             1
12766269                  4                 1  ...      86217.81             1
3586741                   5                 0  ...     123107.16             1
2517343                   4                 0  ...      92797.53             2
4343947                   6                 0  ...     486654.09             2
7702514                  10                 0  ...      90555.30             2
8426703                  11                 0  ...          1.00             2
7765995                  10                 0  ...      51247.62             2
10612569                  1                 1  ...     157046.25             2
10478902                  1                 1  ...     136366.41             0
...                     ...               ...  ...           ...           ...
12062923                  3                 1  ...      72056.04             0
5165674                   7                 0  ...      23022.06             2
6993672                   9                 0  ...      58837.05             1
13060549                  4                 1  ...     241389.09             0
6498626                   9                 0  ...     207773.49             2
11268610                  2                 1  ...     151195.41             1
11782878                  2                 1  ...          1.00             2
6405070                   9                 0  ...     178474.35             1
11908780                  3                 1  ...          1.00             1
1299560                   2                 0  ...     150421.62             1
104028                    0                 0  ...      92480.40             1
11098194                  2                 1  ...      91974.60             1
3432091                   5                 0  ...      49634.76             0
6865602                   9                 0  ...          1.00             1
4903503                   7                 0  ...     233630.01             1
1818059                   2                 0  ...      39351.06             1
5506768                   8                 0  ...     210478.44             1
8710961                  11                 0  ...     148612.65             1
4906824                   7                 0  ...      9970

In [0]:
scaler=sklearn.preprocessing.StandardScaler().fit(X_train[conf])
sc= scaler.transform(X_train[conf])
scaled=pd.DataFrame(sc,columns=conf,index=X_train.index)
X_train_sc=pd.concat([scaled, X_train.drop(conf, axis=1)], axis=1)
X_train_sc.std(axis=0)

Age                       1.000000
Customer seniority        1.000000
Gross income              1.000000
Partitioned Date          3.426785
sex                       0.498214
New customer Index        0.240045
relation at beginning     0.500777
Foreigner index           0.220125
channel to join          55.154836
Province code            12.750240
Activity index            0.499788
segmentation              0.568817
dtype: float64

In [0]:
scaler=sklearn.preprocessing.StandardScaler().fit(X_test[conf])
sc= scaler.transform(X_test[conf])
scaled=pd.DataFrame(sc,columns=conf,index=X_test.index)
X_test_sc=pd.concat([scaled, X_test.drop(conf, axis=1)], axis=1)
X_test_sc.std(axis=0)

Age                       1.000000
Customer seniority        1.000000
Gross income              1.000000
Partitioned Date          3.426246
sex                       0.498157
New customer Index        0.240522
relation at beginning     0.500619
Foreigner index           0.220663
channel to join          55.162008
Province code            12.752998
Activity index            0.499841
segmentation              0.568413
dtype: float64

In [0]:
del(data)
del(train)

In [0]:
class RegressionColumnarDataset(Dataset):
    def __init__(self, df, cats,dy):
        self.dfcats = df[cats]
        self.dfconts = df.drop(cats, axis=1)
        self.dy=dy

        
        self.cats = np.stack([c.values for n, c in self.dfcats.items()], axis=1).astype(np.int64)
        self.conts = np.stack([c.values for n, c in self.dfconts.items()], axis=1).astype(np.float32)
        self.y = np.stack([c.values for n, c in self.dy.items()], axis=1).astype(np.float32)
        
    def __len__(self): return len(self.y)

    def __getitem__(self, idx):
        return [self.cats[idx], self.conts[idx], self.y[idx]]

In [0]:
traind=RegressionColumnarDataset(X_train,catf,y_train)
valds = RegressionColumnarDataset(X_test, catf, y_test)

In [0]:
params = {'batch_size': 256,
          'shuffle': True,
          'num_workers': 8}

traindl = DataLoader(traind, **params)
valdl = DataLoader(valds, **params)

In [0]:
y_range = (0, sum(y_train.max())/len(y_train.columns))
print(y_range)

cat_sz = [(c, X_train[c].max()+1) for c in catf]
print(cat_sz)

emb_szs = [(int(c), int(min(50, (c+1)//2))) for _,c in cat_sz]
print(emb_szs)

(0, 1.0)
[('Partitioned Month', 12), ('Partitioned Year', 2), ('Customer code', 956643), ('sex', 2), ('New customer Index', 2.0), ('relation at beginning', 5), ('Foreigner index', 2), ('channel to join', 162), ('Province code', 53.0), ('Activity index', 3), ('segmentation', 3)]
[(12, 6), (2, 1), (956643, 50), (2, 1), (2, 1), (5, 3), (2, 1), (162, 50), (53, 27), (3, 2), (3, 2)]


In [0]:
del(X_train)
del(y_train)
del(X_test)
del(y_test)
del(traind)
del(valds)

In [0]:
class MixedInputModel(nn.Module):
    def __init__(self, emb_szs, n_cont, emb_drop, out_sz, szs, drops, y_range, use_bn=True):
        super().__init__()
        for i,(c,s) in enumerate(emb_szs): assert c > 1, f"cardinality must be >=2, got emb_szs[{i}]: ({c},{s})"
        self.embs = nn.ModuleList([nn.Embedding(c, s) for c,s in emb_szs])
        for emb in self.embs: emb_init(emb)
        n_emb = sum(e.embedding_dim for e in self.embs)
        self.n_emb, self.n_cont=n_emb, n_cont
        
        szs = [n_emb+n_cont] + szs
        self.lins = nn.ModuleList([nn.Linear(szs[i], szs[i+1]) for i in range(len(szs)-1)])
        self.bns = nn.ModuleList([nn.BatchNorm1d(sz) for sz in szs[1:]])
        for o in self.lins: nn.init.kaiming_normal_(o.weight.data)
        self.outp = nn.Linear(szs[-1], out_sz)
        nn.init.kaiming_normal_(self.outp.weight.data)

        self.emb_drop = nn.Dropout(emb_drop)
        self.drops = nn.ModuleList([nn.Dropout(drop) for drop in drops])
        self.bn = nn.BatchNorm1d(n_cont)
        self.use_bn,self.y_range = use_bn,y_range

    def forward(self, x_cat, x_cont):
        if self.n_emb != 0:
            x = [e(x_cat[:,i]) for i,e in enumerate(self.embs)]
            x = torch.cat(x, 1)
            x = self.emb_drop(x)
        if self.n_cont != 0:
            x2 = self.bn(x_cont)
            x = torch.cat([x, x2], 1) if self.n_emb != 0 else x2
        for l,d,b in zip(self.lins, self.drops, self.bns):
            x = F.relu(l(x))
            if self.use_bn: x = b(x)
            x = d(x)
        x = self.outp(x)
        if self.y_range:
            x = torch.sigmoid(x)
            x = x*(self.y_range[1] - self.y_range[0])
            x = x+self.y_range[0]
        return x.squeeze()

def fit(model, train_dl, val_dl, loss_fn, opt, scheduler, epochs=3):
    num_batch = len(train_dl)
    for epoch in tnrange(epochs):      
        y_true_train = list()
        y_pred_train = list()
        total_loss_train = 0          
        
        t = tqdm_notebook(iter(train_dl), leave=False, total=num_batch)
        for cat, cont, y in t:
            cat = cat.cuda()
            cont = cont.cuda()
            y = y.cuda()
            
            t.set_description(f'Epoch {epoch}')
            
            opt.zero_grad()
            pred = model(cat, cont)
            loss = loss_fn(pred, y)
            loss.backward()
            lr[epoch].append(opt.param_groups[0]['lr'])
            tloss[epoch].append(loss.item())
            scheduler.step()
            opt.step()
            
            t.set_postfix(loss=loss.item())
            
            y_true_train += list(y.cpu().data.numpy())
            y_pred_train += list(pred.cpu().data.numpy())
            total_loss_train += loss.item()
            
        train_acc = rmse(y_true_train, y_pred_train)
        train_loss = total_loss_train/len(train_dl)
        trcorrect=(y_true_train==np.around(y_pred_train,0)).sum()
        traccuracy=(trcorrect/(len(y_true_train)*24))*100

        
        if val_dl:
            y_true_val = list()
            y_pred_val = list()
            total_loss_val = 0
            ts_acc=[]
            for cat, cont, y in tqdm_notebook(val_dl, leave=False):
                cat = cat.cuda()
                cont = cont.cuda()
                y = y.cuda()
                pred = model(cat, cont)
                loss = loss_fn(pred, y)
                
                y_true_val += list(y.cpu().data.numpy())
                y_pred_val += list(pred.cpu().data.numpy())
                
                total_loss_val += loss.item()
                vloss[epoch].append(loss.item())
            valacc = rmse(y_true_val, y_pred_val)
            valloss = total_loss_val/len(valdl)
            
            tscorrect=(y_true_val==np.around(y_pred_val,0)).sum()
            tsaccuracy=(tscorrect/(len(y_true_val)*24))*100
            
            print(f'Epoch {epoch}: train_loss: {train_loss:.4f} train_rmse: {train_acc:.4f} | val_loss: {valloss:.4f} val_rmse: {valacc:.4f}')
            print(f'Training Accuracy {traccuracy:.4f}: Validating accuracy {tsaccuracy:.4f}')
        else:
            print(f'Epoch {epoch}: train_loss: {train_loss:.4f} train_rmse: {train_acc:.4f}')
    
    return lr, tloss, vloss

In [0]:
def emb_init(x):
    x = x.weight.data
    sc = 2/(x.size(1)+1)
    x.uniform_(-sc,sc)

In [0]:
m = MixedInputModel(emb_szs=emb_szs, 
                    n_cont=3, 
                    emb_drop=0.04, 
                    out_sz=24, 
                    szs=[1000,500,250], 
                    drops=[0.001,0.01,0.01], 
                    y_range=y_range).to(torch.device("cuda:0"))

opt = torch.optim.Adam(m.parameters(), 1e-2)
lr_cosine = torch.optim.lr_scheduler.CosineAnnealingLR(opt, 1000)

lr = defaultdict(list)
tloss = defaultdict(list)
vloss = defaultdict(list)

In [0]:
def rmse(targ, y_pred):
    return np.sqrt(sklearn.metrics.mean_squared_error(np.exp(y_pred), np.exp(targ)))

In [0]:
m.train

<bound method Module.train of MixedInputModel(
  (embs): ModuleList(
    (0): Embedding(12, 6)
    (1): Embedding(2, 1)
    (2): Embedding(956643, 50)
    (3): Embedding(2, 1)
    (4): Embedding(2, 1)
    (5): Embedding(5, 3)
    (6): Embedding(2, 1)
    (7): Embedding(162, 50)
    (8): Embedding(53, 27)
    (9): Embedding(3, 2)
    (10): Embedding(3, 2)
  )
  (lins): ModuleList(
    (0): Linear(in_features=147, out_features=1000, bias=True)
    (1): Linear(in_features=1000, out_features=500, bias=True)
    (2): Linear(in_features=500, out_features=250, bias=True)
  )
  (bns): ModuleList(
    (0): BatchNorm1d(1000, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): BatchNorm1d(250, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (outp): Linear(in_features=250, out_features=24, bias=True)
  (emb_drop): Dropout(p=0.04)
  (drops): ModuleList(
    (0): Dropo

In [0]:
loss=nn.BCELoss()
lr, tloss, vloss = fit(model=m, train_dl=traindl, val_dl=valdl, loss_fn=loss, opt=opt, scheduler=lr_cosine, epochs=1)

In [0]:

model = torch.load('/root/recommender/model.pt')
model.eval()

MixedInputModel(
  (embs): ModuleList(
    (0): Embedding(12, 6)
    (1): Embedding(2, 1)
    (2): Embedding(956643, 50)
    (3): Embedding(2, 1)
    (4): Embedding(2, 1)
    (5): Embedding(5, 3)
    (6): Embedding(2, 1)
    (7): Embedding(162, 50)
    (8): Embedding(53, 27)
    (9): Embedding(3, 2)
    (10): Embedding(3, 2)
  )
  (lins): ModuleList(
    (0): Linear(in_features=148, out_features=1000, bias=True)
    (1): Linear(in_features=1000, out_features=500, bias=True)
    (2): Linear(in_features=500, out_features=250, bias=True)
  )
  (bns): ModuleList(
    (0): BatchNorm1d(1000, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (1): BatchNorm1d(500, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
    (2): BatchNorm1d(250, eps=1e-05, momentum=0.1, affine=True, track_running_stats=True)
  )
  (outp): Linear(in_features=250, out_features=24, bias=True)
  (emb_drop): Dropout(p=0.04)
  (drops): ModuleList(
    (0): Dropout(p=0.001)
    (1): Dropout(p

In [0]:
catf=['Partitioned Month','Partitioned Year',"Customer code",'sex','New customer Index', 'relation at beginning','Foreigner index',  'channel to join', 'Province code', 'Activity index','segmentation']
conf=[col for col in test.columns[1:15] if col not in catf]
class TestColumnarDataset(Dataset):
    def __init__(self, df, cats,dy):
        self.dfcats = df[cats]
        self.dfconts = df.drop(cats, axis=1)
        self.dy=dy

        
        self.cats = np.stack([c.values for n, c in self.dfcats.items()], axis=1).astype(np.int64)
        self.conts = np.stack([c.values for n, c in self.dfconts.items()], axis=1).astype(np.float32)
        self.y = np.stack([c.values for n, c in self.dy.items()], axis=1).astype(np.float32)
        
    def __len__(self): return len(self.y)

    def __getitem__(self, idx):
        return [self.cats[idx], self.conts[idx], self.y[idx]]
      
testd=TestColumnarDataset(test.iloc[:,1:15],catf,test.iloc[:,-24:])

In [0]:
params = {'batch_size': 256,
          'shuffle': False,
          'num_workers': 8}

testdl = DataLoader(testd, **params)

In [0]:
tro=torch.tensor([np.array(range(24))])
tro=tro.float().cuda()
t = tqdm_notebook(iter(testdl), leave=False)
for cat, cont,y in t:
  cat = cat.cuda()
  cont = cont.cuda()
  pred = m(cat, cont)
  tro=pro
  del(pred)

In [0]:
d=pd.DataFrame(traindl.dataset.conts)
d.columns=['age','cus','income']
d

age    cus         income
0        74.0    3.0  121641.812500
1        27.0    1.0       1.000000
2        27.0   33.0  117846.453125
3        50.0   32.0   80373.601562
4        20.0    5.0       1.000000
5        42.0  143.0   84269.101562
6        34.0   13.0  115932.867188
7        63.0  177.0  196893.625000
8        50.0  150.0   50217.691406
9        53.0  106.0   57855.871094
10       59.0  193.0  103540.109375
11       24.0   17.0   52455.121094
12       60.0   76.0  166633.171875
13       46.0   79.0  224667.234375
14       54.0   88.0       1.000000
15       49.0   83.0  100088.398438
16       21.0    8.0   55150.140625
17       48.0   83.0       1.000000
18       55.0  115.0  135360.234375
19       25.0   22.0   91499.367188
20       46.0  225.0  209233.171875
21       59.0  110.0   86217.812500
22       44.0  182.0  123107.156250
23       25.0   34.0   92797.531250
24       29.0   43.0  486654.093750
25       21.0   16.0   90555.296875
26       25.0   37.0       1.000000
27       25.0   26.0   51247.621094
28       25.0   43.0  157046.250000
29       58.0  168.0  136366.406250
...       ...    ...            ...
8318272  55.0  238.0   72056.039062
8318273  23.0   35.0   23022.060547
8318274  42.0   87.0   58837.050781
8318275  62.0   20.0  241389.093750
8318276  30.0   36.0  207773.484375
8318277  62.0  173.0  151195.406250
8318278  24.0   43.0       1.000000
8318279  41.0   25.0  178474.343750
8318280  55.0    1.0       1.000000
8318281  39.0  136.0  150421.625000
8318282  47.0   63.0   92480.398438
8318283  54.0  193.0   91974.601562
8318284  65.0   13.0   49634.761719
8318285  76.0  152.0       1.000000
8318286  45.0  117.0  233630.015625
8318287  57.0   33.0   39351.058594
8318288  42.0  143.0  210478.437500
8318289  61.0  117.0  148612.656250
8318290  70.0  113.0   99708.718750
8318291  58.0   90.0       1.000000
8318292  84.0  131.0  365618.000000
8318293  90.0   53.0  222230.671875
8318294  30.0   36.0   69085.437500
8318295  22.0   32.0  105880.796875
8318296  58.0  165.0  200880.593750
8318297  38.0    4.0  101325.812500
8318298  29.0   58.0  109596.148438
8318299  22.0   31.0   94114.437500
8318300  41.0  169.0  103330.078125
8318301  53.0  108.0  116095.046875

[8318302 rows x 3 columns]

In [0]:
tro.cpu()

RuntimeError: ignored

In [0]:
U = user_emb(users)
V = item_emb(items)

In [0]:
for i in np.around(m(cat,cont).cpu().data.numpy()):
  print(i)

[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
[0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0

In [0]:
num_users = len(df_train.userId.unique())
num_items = len(df_train.movieId.unique())
print(num_users, num_items)

610 8998


In [0]:
model = MF(num_users, num_items, emb_size=100)

In [0]:
def train_epocs(model, epochs=10, lr=0.01, wd=0.0, unsqueeze=False):
    optimizer = torch.optim.Adam(model.parameters(), lr=lr, weight_decay=wd)
    model.train()
    for i in range(epochs):
        users = torch.LongTensor(df_train.userId.values) # .cuda()
        items = torch.LongTensor(df_train.movieId.values) #.cuda()
        ratings = torch.FloatTensor(df_train.rating.values) #.cuda()
        if unsqueeze:
            ratings = ratings.unsqueeze(1)
        y_hat = model(users, items)
        loss = F.mse_loss(y_hat, ratings)
        optimizer.zero_grad()
        loss.backward()
        optimizer.step()
        print(loss.item()) 
    test_loss(model, unsqueeze)

In [0]:
ratings = torch.FloatTensor(df_train.rating.values)
print(ratings.shape)
ratings = ratings.unsqueeze(1) # .cuda()
print(ratings.shape)

torch.Size([80450])
torch.Size([80450, 1])


In [0]:
def test_loss(model, unsqueeze=False):
    model.eval()
    users = torch.LongTensor(df_val.userId.values) #.cuda()
    items = torch.LongTensor(df_val.movieId.values) #.cuda()
    ratings = torch.FloatTensor(df_val.rating.values) #.cuda()
    if unsqueeze:
        ratings = ratings.unsqueeze(1)
    y_hat = model(users, items)
    loss = F.mse_loss(y_hat, ratings)
    print("test loss %.3f " % loss.item())

In [0]:
train_epocs(model, epochs=15, lr=0.01)

12.909751892089844
12.503971099853516
11.975833892822266
11.333617210388184
10.586678504943848
9.746391296386719
8.826869010925293
7.8455705642700195
6.823812484741211
5.787166118621826
4.76566219329834
3.7936084270477295
2.908734083175659
2.150165557861328
1.5545402765274048
test loss 1.169 


In [0]:
class MF_bias(nn.Module):
    def __init__(self, num_users, num_items, emb_size=100):
        super(MF_bias, self).__init__()
        self.user_emb = nn.Embedding(num_users, emb_size)
        self.user_bias = nn.Embedding(num_users, 1)
        self.item_emb = nn.Embedding(num_items, emb_size)
        self.item_bias = nn.Embedding(num_items, 1)
        self.user_emb.weight.data.uniform_(0,0.05)
        self.item_emb.weight.data.uniform_(0,0.05)
        self.user_bias.weight.data.uniform_(-0.01,0.01)
        self.item_bias.weight.data.uniform_(-0.01,0.01)
        
    def forward(self, u, v):
        U = self.user_emb(u)
        V = self.item_emb(v)
        b_u = self.user_bias(u).squeeze()
        b_v = self.item_bias(v).squeeze()
        return (U*V).sum(1) +  b_u  + b_v

In [0]:
model = MF_bias(num_users, num_items, emb_size=100)

In [0]:
train_epocs(model, epochs=15, lr=0.001, wd=1e-5)

12.913296699523926
12.86480712890625
12.814960479736328
12.763782501220703
12.711271286010742
12.657415390014648
12.602203369140625
12.54561996459961
12.487649917602539
12.428277015686035
12.367485046386719
12.305256843566895
12.241578102111816
12.176431655883789
12.10980224609375
test loss 12.130 


In [0]:
class CollabFNet(nn.Module):
    def __init__(self, num_users, num_items, emb_size=100, n_hidden=10):
        super(CollabFNet, self).__init__()
        self.user_emb = nn.Embedding(num_users, emb_size)
        self.item_emb = nn.Embedding(num_items, emb_size)
        self.lin1 = nn.Linear(emb_size*2, n_hidden)
        self.lin2 = nn.Linear(n_hidden, 1)
        self.drop1 = nn.Dropout(0.1)
        
    def forward(self, u, v):
        U = self.user_emb(u)
        V = self.item_emb(v)
        x = F.relu(torch.cat([U, V], dim=1))
        x = self.drop1(x)
        x = F.relu(self.lin1(x))
        x = self.lin2(x)
        return x

In [0]:
model = CollabFNet(num_users, num_items, emb_size=100) #.cuda()

In [0]:
!git clone https://github.com/HarshdeepGupta/recommender_pytorch.git

Cloning into 'recommender_pytorch'...
remote: Enumerating objects: 19, done.
remote: Total 19 (delta 0), reused 0 (delta 0), pack-reused 19
Unpacking objects: 100% (19/19), done.


In [0]:
cd /content/recommender_pytorch

/content/recommender_pytorch


In [0]:
!python train_test_split.py

Size of the entire dataset:(100000, 4)
train_test_split.py:32: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  train_df.sort_values(by=["userID", 'timestamp'], inplace = True)
train_test_split.py:33: SettingWithCopyWarning: 
A value is trying to be set on a copy of a slice from a DataFrame

See the caveats in the documentation: http://pandas.pydata.org/pandas-docs/stable/indexing.html#indexing-view-versus-copy
  test_df.sort_values(by=["userID", 'timestamp'], inplace = True)
Saving df to path: Data/movielens.train.rating
Columns in df are: ['userID', 'movieID', 'rating', 'timestamp']
Saving df to path: Data/movielens.test.rating
Columns in df are: ['userID', 'movieID', 'rating', 'timestamp']
Total No. of Records = 100000.0
Train size = 99057, Test size = 943
Train % = 0.99057, Test % =0.00943


In [0]:
!python itempop.py

Model arguments: Namespace(dataset='movielens', num_neg_test=100, path='Data/') 
Load data done [3.2 s]. #user=944, #item=1683, #train=99057, #test=943
Eval: HR = 0.4062, NDCG = 0.2199 [0.1 s]


In [0]:
!python MLP.py

Device available: cuda:0
MLP arguments: Namespace(batch_size=256, dataset='movielens', dropout=0, epochs=30, layers='[16,32,16,8]', learner='adam', lr=0.001, num_neg_test=100, num_neg_train=4, out=1, path='Data/', verbose=1, weight_decay=1e-05) 
Load data done [2.8 s]. #user=944, #item=1683, #train=99057, #test=943
MLP(
  (user_embedding): Embedding(944, 8)
  (item_embedding): Embedding(1683, 8)
  (fc_layers): ModuleList(
    (0): Linear(in_features=16, out_features=32, bias=True)
    (1): Linear(in_features=32, out_features=16, bias=True)
    (2): Linear(in_features=16, out_features=8, bias=True)
  )
  (output_layer): Linear(in_features=8, out_features=1, bias=True)
)
Eval: HR = 0.0965, NDCG = 0.0424 [1.1 s]
Epoch = 0
Epoch completed 8.7 s
Train Loss: 0.4413356633765445
Eval: HR = 0.3818, NDCG = 0.2005 [1.1 s]
Epoch = 1
Epoch completed 8.5 s
Train Loss: 0.3639196495831167
Eval: HR = 0.3966, NDCG = 0.2139 [1.1 s]
Epoch = 2



In [0]:
!git clone https://github.com/maciejkula/spotlight.git

Cloning into 'spotlight'...
remote: Enumerating objects: 16, done.
remote: Counting objects: 100% (16/16), done.
remote: Compressing objects: 100% (12/12), done.
remote: Total 3218 (delta 4), reused 7 (delta 4), pack-reused 3202
Receiving objects: 100% (3218/3218), 8.83 MiB | 5.18 MiB/s, done.
Resolving deltas: 100% (2094/2094), done.


In [0]:
import pandas as pd
import numpy as np
import torch
dy=pd.DataFrame({'Sam':[1,2,3],'Lam':[3,2,1],'Preetham':[2,3,1]})
y = np.stack([c.values for n, c in dy.items()], axis=1).astype(np.float32)
t=torch.tensor(y)
for i in t.data.numpy():
  p=(list(i).index(max(i)))
  dic={1:'Sam',2:'Lam',0:'Preetham'}
  print(dic[p])

Sam
Lam
Preetham


In [0]:
for epoch in ["ncodpers","age","ind_nuevo","antiguedad","cod_prov","ind_actividad_cliente","renta","sexo_index","tiprel_1mes_index","indext_index","canal_entrada_index","segmento_index","fecha_year","fecha_month","total"]:

  print(fr'C:\Users\samuel.preethamlam\Desktop\Pyspark\{epoch}')

C:\Users\samuel.preethamlam\Desktop\Pyspark\ncodpers
C:\Users\samuel.preethamlam\Desktop\Pyspark\age
C:\Users\samuel.preethamlam\Desktop\Pyspark\ind_nuevo
C:\Users\samuel.preethamlam\Desktop\Pyspark\antiguedad
C:\Users\samuel.preethamlam\Desktop\Pyspark\cod_prov
C:\Users\samuel.preethamlam\Desktop\Pyspark\ind_actividad_cliente
C:\Users\samuel.preethamlam\Desktop\Pyspark\renta
C:\Users\samuel.preethamlam\Desktop\Pyspark\sexo_index
C:\Users\samuel.preethamlam\Desktop\Pyspark\tiprel_1mes_index
C:\Users\samuel.preethamlam\Desktop\Pyspark\indext_index
C:\Users\samuel.preethamlam\Desktop\Pyspark\canal_entrada_index
C:\Users\samuel.preethamlam\Desktop\Pyspark\segmento_index
C:\Users\samuel.preethamlam\Desktop\Pyspark\fecha_year
C:\Users\samuel.preethamlam\Desktop\Pyspark\fecha_month
C:\Users\samuel.preethamlam\Desktop\Pyspark\total
